services:

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password


  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI="mongo"
    ports:
      - "3000:3000"