{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-exporter.fullname" . }}
  labels:
    app: {{ include "mongodb-exporter.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "mongodb.chart" . }}
type: Opaque
data:
  mongodb-uri: {{ required "A MongoDB URI is required" .Values.exporter.mongodb.uri | b64enc }}
{{- end }}
